version: '3.8'

services:

  mariadb:
    container_name: maria-db
    image: mariadb:10.6.4-focal
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: keycloak
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    volumes: 
      - mariadb_data:/var/lib/mysql
    networks:
      - box_key_network

networks:
  box_key_network: {}

volumes: 
  mariadb_data:
    driver: local
